export const LANGUAGES = [
  'English',
  'Spanish',
  'French',
  'German',
  'Italian',
  'Portuguese',
  'Russian',
  'Japanese',
  'Korean',
  'Chinese (Mandarin)',
  'Chinese (Cantonese)',
  'Arabic',
  'Hindi',
  'Dutch',
  'Swedish',
  'Norwegian',
  'Danish',
  'Finnish',
  'Polish',
  'Czech',
  'Hungarian',
  'Romanian',
  'Bulgarian',
  'Greek',
  'Turkish',
  'Hebrew',
  'Thai',
  'Vietnamese',
  'Indonesian',
  'Tagalog',
] as const

export const ROUTES = {
  LANDING: '/',
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  HOME: '/app/home',
  CONNECT: '/app/connect',
  PROFILE: '/app/profile',
  FEED: '/app/feed',
  MATCHES: '/app/matches',
  INCOMING_REQUESTS: '/app/requests/incoming',
  OUTGOING_REQUESTS: '/app/requests/outgoing',
} as const

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    ME: '/users/me',
    GOOGLE: '/auth/google',
    GOOGLE_CALLBACK: '/auth/google/callback',
  },
  USERS: {
    UPDATE_LANGUAGES: '/users/me/languages',
    UPDATE_PROFILE: '/users/me/profile',
    SEARCH: '/users',
  },
  MATCHES: {
    SEND_REQUEST: '/matches/requests',
    INCOMING_REQUESTS: '/matches/requests/incoming',
    OUTGOING_REQUESTS: '/matches/requests/outgoing',
    HANDLE_REQUEST: (id: string) => `/matches/requests/${id}`,
    MATCHES: '/matches',
  },
} as const